---
- hosts: all
  become: true
  gather_facts: false
  vars: 
    source: "files/replicate"
    destination: "/tmp"
  tasks:

    - name: grab dir structure of /var/lib/
      ansible.builtin.shell: 
        cmd: "pwd; ls -al ."
      register: tree
      #delegate_to: localhost

    - name: print dir structure of /var/lib/
      ansible.builtin.debug:
        var: tree.stdout_lines
      #delegate_to: localhost
        
    - name: transfer file to remote location
      ansible.builtin.copy:
        src: "/runner/project/{{ source }}"
        dest: "{{ destination }}"
        backup: yes
