---
- hosts: all
  become: true
  gather_facts: false
  vars: 
    source: "/var/lib/awx/projects/files/replicate"
    destination: "/tmp"
  tasks:

    - name: grab dir structure of /var/lib/
      ansible.builtin.shell: 
        cmd: "ls -al /var/lib/"
      register: tree
      #delegate_to: localhost

    - name: print dir structure of /var/lib/
      ansible.builtin.debug:
        var: tree.stdout_lines
      #delegate_to: localhost
        
    - name: transfer file to remote location
      ansible.builtin.copy:
        src: "{{ source }}"
        dest: "{{ destination }}"
        backup: yes
