---
- name: Get Uptime
  hosts: all
  gather_facts: true
  vars:
    csv_filename: "report.csv"
    headers: "Hostname,Uptime_In_Days"
  tasks:

  - name: Write uptime in CSV
    ansible.builtin.debug:
      #msg: "{{ ansible_facts.hostname }},{{ ansible_facts.uptime_seconds / 86400 | int }}"
      msg: "{{ hostvars[item]['ansible_facts']['fqdn'] }},{{ hostvars[item]['ansible_facts']['uptime_seconds'] / 86400 | int }}"  
    loop: "{{ groups['all'] }}"

  - name: Write uptime in CSV
    ansible.builtin.lineinfile:
      dest: "/tmp/uptime.csv"
      line: "{{ hostvars[item]['ansible_facts']['fqdn'] }},{{ hostvars[item]['ansible_facts']['uptime_seconds'] / 86400 | int }}"
      create: true 
      state: present
    delegate_to: localhost
    loop: "{{ groups['all'] }}"
