################################################################################
# The following information has been provided by Red Hat, but is outside the   #
# scope of the posted Service Level Agreements and support procedures          #
# (https://access.redhat.com/support/offerings/production/). The information   #
# is provided as-is and any configuration settings or installed applications   #
# made from the information in this article could make the Operating System    #
# unsupported by Red Hat Global Support Services. The intent of this article   #
# is to provide information to accomplish the system's needs. Use of the       #
# information in this article at the user's own risk.                          #
################################################################################

---
- name: Get Uptime
  hosts: all
  gather_facts: true
  tasks:

  - name: Template 
    ansible.builtin.template:
      src: /runner/project/templates/uptime.j2
      dest: /tmp/uptime.csv
    delegate_to: localhost

- name: Get Uptime
  hosts: controller.beaverdam.com
  gather_facts: false
  become: true
  tasks:

  - name: Push generated CSV file to controller
    ansible.builtin.copy:
      src: /tmp/uptime.csv
      dest: /tmp/uptime.csv
      owner: root
      mode: '0644'
